version: '3.8'
services:
  app:
    build: .
    container_name: python-batch-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
